from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.utils import shuffle
import joblib

# Dữ liệu huấn luyện
training_data = [
    ("Giới tính của con tôi là nam.","nam"),
    ("Con mình là nữ.","nữ"),
    ("Con tôi là bé trai.","nam"),
    ("Giới tính của con là bé gái.","nữ"),
    ("Con tôi là nam.","nam"),
    ("Con mình là bé trai.","nam"),
    ("Giới tính của con là nam.","nam"),
    ("Con tôi là nữ.","nữ"),
    ("Con mình là bé gái.","nữ"),
    ("Giới tính của con là nữ.","nữ"),
    ("Con trai của tôi bị suy dinh dưỡng","nam"),
    ("Thằng cu con nhà tôi bị suy dinh dưỡng","nam"),
    ("Con trai của tôi bị suy dinh dưỡng","nam"),
    ("Con gái của tôi bị suy dinh dưỡng","nữ"),
    ("Con gái của tôi bị mẹ đánh ","nam"),
    ("Con trai của tôi rất thông minh","nam"),
    ("Con trai của tôi bị đau chân","nam"),
    ("Con trai của tôi bị ngã xe","nam"),
    ("Con của tôi bị suy dinh dưỡng","nam"),
    ("Thằng cu con nhà tôi bị suy dinh dưỡng","nam"),
    ("Con của tôi bị suy dinh dưỡng","không"),
    ("Con nhà tôi bị suy dinh dưỡng","không"),
    ("Con của tôi bị mẹ đánh ","không"),
    ("Con của tôi rất thông minh","không"),
    ("Con của tôi bị đau chân","không"),
    ("Con của tôi bị ngã xe","không"),
    ("Con bé ho đêm.","nữ"),
    ("Con ốm nặng, sốt cao.","không"),
    ("Con khó thở.","không"),
    ("Con bé đau bụng.","nữ"),
    ("Con bị kích ứng da.","không"),
    ("Con bé mệt mỏi,.","nữ"),
    ("Con bé nôn mửa.","nữ"),
    ("Con đau tai.","không"),
    ("Con bé ho ra máu.","nữ"),
    ("Con bị cảm lạnh.","không"),
    ("Con nhà tôi ốm nặng, sốt cao.","không"),
    ("Con nhà tôi khó thở.","không"),
    ("Con nhà tôi bé đau bụng.","không"),
    ("Con nhà tôi bị kích ứng da.","không"),
    ("Con nhà tôi bé mệt mỏi,.","không"),
    ("Con nhà tôi bé nôn mửa.","không"),
    ("Con nhà tôi đau tai.","không"),
    ("Con nhà tôi bé ho ra máu.","không"),
    ("Con nhà tôi bị cảm lạnh.","không"),
    ("Con trai của tôi bị suy dinh dưỡng","nam"),
    ("Con trai nhà tôi bị suy dinh dưỡng","nam"),
    ("Con trai của tôi bị mẹ đánh ","nam"),
    ("Con trai của tôi rất thông minh","nam"),
    ("Con trai của tôi bị đau chân","nam"),
    ("Con trai của tôi bị ngã xe","nam"),
    ("Con trai bé ho đêm.","nam"),
    ("Con trai ốm nặng, sốt cao.","nam"),
    ("Con trai khó thở.","nam"),
    ("Con trai bé đau bụng.","nam"),
    ("Con trai bị kích ứng da.","nam"),
    ("Con trai bé mệt mỏi,.","nam"),
    ("Con trai bé nôn mửa.","nam"),
    ("Con trai đau tai.","nam"),
    ("Con trai bé ho ra máu.","nam"),
    ("Con trai bị cảm lạnh.","nam"),
    ("Con trai nhà tôi ốm nặng, sốt cao.","nam"),
    ("Con trai nhà tôi khó thở.","nam"),
    ("Con trai nhà tôi bé đau bụng.","nam"),
    ("Con trai nhà tôi bị kích ứng da.","nam"),
    ("Con trai nhà tôi bé mệt mỏi,.","nam"),
    ("Con trai nhà tôi bé nôn mửa.","nam"),
    ("Con trai nhà tôi đau tai.","nam"),
    ("Con trai nhà tôi bé ho ra máu.","nam"),
    ("Con trai nhà tôi bị cảm lạnh.","nam"),
    ("Con trai của tôi bị suy dinh dưỡng","nam"),
    ("Con gái nhà tôi bị suy dinh dưỡng","nữ"),
    ("Con gái của tôi bị mẹ đánh ","nữ"),
    ("Con gái của tôi rất thông minh","nữ"),
    ("Con gái của tôi bị đau chân","nữ"),
    ("Con gái của tôi bị ngã xe","nữ"),
    ("Con gái bé ho đêm.","nữ"),
    ("Con gái ốm nặng, sốt cao.","nữ"),
    ("Con gái khó thở.","nữ"),
    ("Con gái bé đau bụng.","nữ"),
    ("Con gái bị kích ứng da.","nữ"),
    ("Con gái bé mệt mỏi,.","nữ"),
    ("Con gái bé nôn mửa.","nữ"),
    ("Con gái đau tai.","nữ"),
    ("Con gái bé ho ra máu.","nữ"),
    ("Con gái bị cảm lạnh.","nữ"),
    ("Con gái nhà tôi ốm nặng, sốt cao.","nữ"),
    ("Con gái nhà tôi khó thở.","nữ"),
    ("Con gái nhà tôi bé đau bụng.","nữ"),
    ("Con gái nhà tôi bị kích ứng da.","nữ"),
    ("Con gái nhà tôi bé mệt mỏi,.","nữ"),
    ("Con gái nhà tôi bé nôn mửa.","nữ"),
    ("Con gái nhà tôi đau tai.","nữ"),
    ("Con gái nhà tôi bé ho ra máu.","nữ"),
    ("Con gái nhà tôi bị cảm lạnh.","nữ"),         
    ("Con gái nhà tôi bị suy dinh dưỡng","nữ"),
    ("Con bé nhà tôi bị suy dinh dưỡng","nữ"),
    ("Con bé của tôi bị mẹ đánh ","nữ"),
    ("Con bé của tôi rất thông minh","nữ"),
    ("Con bé của tôi bị đau chân","nữ"),
    ("Con bé của tôi bị ngã xe","nữ"),
    ("Con bé bé ho đêm.","nữ"),
    ("Con bé ốm nặng, sốt cao.","nữ"),
    ("Con bé khó thở.","nữ"),
    ("Con bé bé đau bụng.","nữ"),
    ("Con bé bị kích ứng da.","nữ"),
    ("Con bé bé mệt mỏi,.","nữ"),
    ("Con bé bé nôn mửa.","nữ"),
    ("Con bé đau tai.","nữ"),
    ("Con bé bé ho ra máu.","nữ"),
    ("Con bé bị cảm lạnh.","nữ"),
    ("Con bé nhà tôi ốm nặng, sốt cao.","nữ"),
    ("Con bé nhà tôi khó thở.","nữ"),
    ("Con bé nhà tôi bé đau bụng.","nữ"),
    ("Con bé nhà tôi bị kích ứng da.","nữ"),
    ("Con bé nhà tôi bé mệt mỏi,.","nữ"),
    ("Con bé nhà tôi bé nôn mửa.","nữ"),
    ("Con bé nhà tôi đau tai.","nữ"),
    ("Con bé nhà tôi bé ho ra máu.","nữ"),
    ("Con bé nhà tôi bị cảm lạnh.","nữ"),         
    ("Con bé nhà tôi bị suy dinh dưỡng","nữ"),
    ("Bé gái nhà tôi bị suy dinh dưỡng","nữ"),
    ("Bé gái của tôi bị mẹ đánh ","nữ"),
    ("Bé gái của tôi rất thông minh","nữ"),
    ("Bé gái của tôi bị đau chân","nữ"),
    ("Bé gái của tôi bị ngã xe","nữ"),
    ("Bé gái bé ho đêm.","nữ"),
    ("Bé gái ốm nặng, sốt cao.","nữ"),
    ("Bé gái khó thở.","nữ"),
    ("Bé gái bé đau bụng.","nữ"),
    ("Bé gái bị kích ứng da.","nữ"),
    ("Bé gái bé mệt mỏi,.","nữ"),
    ("Bé gái bé nôn mửa.","nữ"),
    ("Bé gái đau tai.","nữ"),
    ("Bé gái bé ho ra máu.","nữ"),
    ("Bé gái bị cảm lạnh.","nữ"),
    ("Bé gái nhà tôi ốm nặng, sốt cao.","nữ"),
    ("Bé gái nhà tôi khó thở.","nữ"),
    ("Bé gái nhà tôi bé đau bụng.","nữ"),
    ("Bé gái nhà tôi bị kích ứng da.","nữ"),
    ("Bé gái nhà tôi bé mệt mỏi,.","nữ"),
    ("Bé gái nhà tôi bé nôn mửa.","nữ"),
    ("Bé gái nhà tôi đau tai.","nữ"),
    ("Bé gái nhà tôi bé ho ra máu.","nữ"),
    ("Bé gái nhà tôi bị cảm lạnh.","nữ"),         
    ("Bé gái nhà tôi bị suy dinh dưỡng","nữ"),
    ("Thằng bé của tôi bị mẹ đánh ","nam"),
    ("Thằng bé của tôi rất thông minh","nam"),
    ("Thằng bé của tôi bị đau chân","nam"),
    ("Thằng bé của tôi bị ngã xe","nam"),
    ("Thằng bé bé ho đêm.","nam"),
    ("Thằng bé ốm nặng, sốt cao.","nam"),
    ("Thằng bé khó thở.","nam"),
    ("Thằng bé bé đau bụng.","nam"),
    ("Thằng bé bị kích ứng da.","nam"),
    ("Thằng bé bé mệt mỏi,.","nam"),
    ("Thằng bé bé nôn mửa.","nam"),
    ("Thằng bé đau tai.","nam"),
    ("Thằng bé bé ho ra máu.","nam"),
    ("Thằng bé bị cảm lạnh.","nam"),
    ("Thằng bé nhà tôi ốm nặng, sốt cao.","nam"),
    ("Thằng bé nhà tôi khó thở.","nam"),
    ("Thằng bé nhà tôi bé đau bụng.","nam"),
    ("Thằng bé nhà tôi bị kích ứng da.","nam"),
    ("Thằng bé nhà tôi bé mệt mỏi,.","nam"),
    ("Thằng bé nhà tôi bé nôn mửa.","nam"),
    ("Thằng bé nhà tôi đau tai.","nam"),
    ("Thằng bé nhà tôi bé ho ra máu.","nam"),
    ("Thằng bé nhà tôi bị cảm lạnh.","nam"),         
    ("Thằng bé nhà tôi bị suy dinh dưỡng","nam"),
    ("Thằng cu của tôi bị mẹ đánh ","nam"),
    ("Thằng cu của tôi rất thông minh","nam"),
    ("Thằng cu của tôi bị đau chân","nam"),
    ("Thằng cu của tôi bị ngã xe","nam"),
    ("Thằng cu bé ho đêm.","nam"),
    ("Thằng cu ốm nặng, sốt cao.","nam"),
    ("Thằng cu khó thở.","nam"),
    ("Thằng cu bé đau bụng.","nam"),
    ("Thằng cu bị kích ứng da.","nam"),
    ("Thằng cu bé mệt mỏi,.","nam"),
    ("Thằng cu bé nôn mửa.","nam"),
    ("Thằng cu đau tai.","nam"),
    ("Thằng cu bé ho ra máu.","nam"),
    ("Thằng cu bị cảm lạnh.","nam"),
    ("Thằng cu nhà tôi ốm nặng, sốt cao.","nam"),
    ("Thằng cu nhà tôi khó thở.","nam"),
    ("Thằng cu nhà tôi bé đau bụng.","nam"),
    ("Thằng cu nhà tôi bị kích ứng da.","nam"),
    ("Thằng cu nhà tôi bé mệt mỏi,.","nam"),
    ("Thằng cu nhà tôi bé nôn mửa.","nam"),
    ("Thằng cu nhà tôi đau tai.","nam"),
    ("Thằng cu nhà tôi bé ho ra máu.","nam"),
    ("Thằng cu nhà tôi bị cảm lạnh.","nam"),         
    ("Thằng cu nhà tôi bị suy dinh dưỡng","nam")

   
    # Thêm các câu mô tả khác về con trai và con gái
]

# Tách dữ liệu thành các câu nói và nhãn
texts, labels = zip(*training_data)
# Xáo trộn dữ liệu
texts, labels = shuffle(texts, labels, random_state=42)
# Tạo model và train
model = make_pipeline(CountVectorizer(), MultinomialNB())
model.fit(texts, labels)



# Lưu model vào file
joblib.dump(model, 'gender_classification_model.joblib')

# Gọi model từ file
loaded_model = joblib.load('gender_classification_model.joblib')

# Dự đoán giới tính của một câu nói
# text_to_predict = "Con bé nhà tôi bị suy dinh dưỡng"
while(True):
    text_to_predict = input("Nhập nội dung: ")
    predicted_gender = loaded_model.predict([text_to_predict])
    predicted_prob = loaded_model.predict_proba([text_to_predict])
    print(predicted_gender)  # Kết quả sẽ là "nam" hoặc "nữ"
    confidence_male = predicted_prob[0][loaded_model.classes_ == "nam"]
    confidence_female = predicted_prob[0][loaded_model.classes_ == "nữ"]
    print(confidence_male)
    print(confidence_female)
